Fix test framework error causing "AttributeError: Popen instance has no attribute '_clean'"
git-svn-id: https://svn.apache.org/repos/asf/qpid/trunk@963409 13f79535-47bb-0310-9956-ffa450edef68